Creating package
greenpress/api-proxy-middleware pull request #3
Opened 2021-05-10 12:48 UTC by or-yam

@davidmeirlevy Please take a look and let me know what you think. 
I didn't completely understand how to auto-generate configuration from environment variables.
Once we done with the review I will publish it to npm.

2021-05-10 13:24 UTC, davidmeirlevy requested changes

2021-05-10 13:24 UTC, davidmeirlevy commented on index.js
> +const app = require('express');
no.

2021-05-10 13:24 UTC, davidmeirlevy commented on index.js
> +module.exports = function apiProxy(config) {
this function should get the app as a first parameter, and the config is second.

2021-05-10 13:24 UTC, davidmeirlevy commented on index.js
> +  const { authService, contentService, adminPanel, assetsService, tenant, draftsService, applicationUrl } = config;
this package should also build its own config.
you should also take those objects from the original config file at the `blog-front` and put them inside this package (use a config.js file).

2021-05-10 13:24 UTC, davidmeirlevy commented on index.js
> +        req.user = user;
I found out a better way of doing this line :)

you can put this user on the headers directly, like: `req.headers.user = user` and then you can also remove the `onProxyReq ` function, and its usage.

2021-05-10 13:24 UTC, davidmeirlevy commented on index.js
> +      onProxyReq
read my comment regarding this function :)

2021-05-10 13:24 UTC, davidmeirlevy commented on package.json
> +{
look at this package.json for a good reference to a package:
https://github.com/greenpress/api-kit/blob/master/package.json

- no need for scripts
- no need for "nodemon"
- no need "express" as a dependency (but as a peerDependency).
- the license should be MIT.
- missing "main" property here.
- also take the license, contributing, .editorconfig, .gitignore, and readme file from the api-kit package.

2021-05-10 14:09 UTC, or-yam commented on index.js
> +  const { authService, contentService, adminPanel, assetsService, tenant, draftsService, applicationUrl } = config;
Do you mean something like [this](https://github.com/greenpress/blog-front/blob/master/config/index.js) file ?

2021-05-13 18:27 UTC, davidmeirlevy commented on index.js
> +  const { authService, contentService, adminPanel, assetsService, tenant, draftsService, applicationUrl } = config;
Yes

2021-05-13 18:31 UTC, davidmeirlevy requested changes
Last minor changes..

2021-05-13 18:31 UTC, davidmeirlevy commented on package.json
> +    "express": "^4.17.1"
At peer you should use ">=x.y.z"

2021-05-15 13:47 UTC, or-yam commented
@davidmeirlevy Updated with the requested changes.

2021-05-15 19:16 UTC, davidmeirlevy requested changes

2021-05-15 19:16 UTC, davidmeirlevy commented on config.js
> +  alternativeHmr: !!process.env.ALTERNATIVE_HMR,
This variable isn't needed here.

2021-05-15 19:16 UTC, davidmeirlevy commented on config.js
> +  port: process.env.PORT || 3000,
This variable isn't needed here.

2021-05-15 19:16 UTC, davidmeirlevy commented on index.js
> +  const services = Object.keys({ ...configFile }).map((service) => config[service] || configFile[service]);
There are better ways to extend an object in JS.

2021-05-15 22:13 UTC, or-yam commented on index.js
> +  const services = Object.keys({ ...configFile }).map((service) => config[service] || configFile[service]);
Fixed.

2021-05-16 06:32 UTC, davidmeirlevy approved these changes

2021-05-16 06:33 UTC, merged